# Generated by Django 6.0 on 2026-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='profile_photos/default_picture.jpg', upload_to='profile_photos/'),
        ),
    ]
