# Generated by Django 6.0 on 2026-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_obj',
            field=models.CharField(choices=[('P', 'Post'), ('T', 'Topic'), ('B', 'Blog'), ('U', 'USD Citizenship request')], max_length=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('C', 'Created'), ('E', 'Edited'), ('D', 'Deleted'), ('S', 'Sent')], max_length=1),
        ),
    ]
