# Generated by Django 6.0 on 2026-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_admin_alter_activity_action_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_citizen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_obj',
            field=models.CharField(choices=[('P', 'Post'), ('T', 'Topic'), ('B', 'Blog'), ('U', 'USD Citizenship request'), ('P', 'Petition')], max_length=1),
        ),
    ]
