# Generated by Django 6.0 on 2026-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_citizen_alter_activity_action_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_obj',
            field=models.CharField(choices=[('P', 'Post'), ('T', 'Topic'), ('B', 'Blog'), ('U', 'USD Citizenship request'), ('E', 'Petition')], max_length=1),
        ),
    ]
