# Generated by Django 6.0 on 2026-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_activity_action_obj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="private",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
