# Generated by Django 6.0 on 2026-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_citizen",
            field=models.BooleanField(default=False),
        ),
    ]
