# Generated by Django 6.0 on 2026-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_profile_is_admin_alter_profile_is_citizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="private",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
