# Generated by Django 6.0 on 2026-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_profile_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="private",
            field=models.BooleanField(default=True),
        ),
    ]
