# Generated by Django 6.0 on 2026-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_profile_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
