# Generated by Django 6.0 on 2026-09-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.style'),
        ),
    ]
