# Generated by Django 6.0 on 2026-09-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_style_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='style_selected',
            new_name='style',
        ),
    ]
