# Generated by Django 6.0 on 2026-09-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_style_selected_profile_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_obj',
            field=models.CharField(choices=[('P', 'Post'), ('T', 'Topic'), ('B', 'Blog'), ('U', 'USD Citizenship request'), ('E', 'Petition'), ('S', 'Style')], max_length=1),
        ),
    ]
