# Generated by Django 6.0 on 2026-03-04 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USDCitizenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('N', 'Not processed yet')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q0answer', models.CharField(max_length=50)),
                ('q1answer', models.CharField(max_length=100)),
                ('q2answer', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
