# Generated by Django 6.0 on 2026-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdcitizenrequest',
            name='due_to',
            field=models.TextField(blank=True),
        ),
    ]
