# Generated by Django 6.0 on 2025-12-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogtopicrelation',
            unique_together={('topic', 'blog')},
        ),
    ]
