# Generated by Django 6.0 on 2026-01-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'media'},
        ),
    ]
