# Generated by Django 6.0 on 2026-01-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_media_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='file_field',
        ),
    ]
