# Generated by Django 6.0 on 2026-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_field',
            field=models.FileField(upload_to='post_media/'),
        ),
    ]
