# Generated by Django 6.0 on 2026-02-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_reaction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='blogs.post'),
        ),
    ]
