# Generated by Django 6.0 on 2026-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_alter_blog_owner_alter_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
